name: drupal9
recipe: drupal9
config:
  webroot: docroot
services:
  appserver:
    type: php:8.0
    webroot: docroot
    config:
      php: .lando/php.ini
    build:
      - composer install
  database:
    type: mariadb:10.5
  solr:
    type: solr
  phpmyadmin:
    type: phpmyadmin:5.1
